DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS AUDITORIUM;
GO

DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS PULPIT;
DROP TABLE IF EXISTS AUDITORIUM_TYPE;
GO

DROP TABLE IF EXISTS FACULTY;
GO


CREATE TABLE FACULTY (
    FACULTY NVARCHAR(100) NOT NULL PRIMARY KEY, 
    FACULTY_NAME NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE PULPIT (
    PULPIT NVARCHAR(100) NOT NULL PRIMARY KEY, 
    PULPIT_NAME NVARCHAR(100) NOT NULL,
    FACULTY NVARCHAR(100) NOT NULL, 
    CONSTRAINT FK_PULPIT_FACULTY FOREIGN KEY (FACULTY)
        REFERENCES FACULTY(FACULTY) ON DELETE CASCADE
);
GO

CREATE TABLE SUBJECT (
    SUBJECT NVARCHAR(100) NOT NULL PRIMARY KEY,
    SUBJECT_NAME NVARCHAR(100) NOT NULL,
    PULPIT NVARCHAR(100) NOT NULL, 
    CONSTRAINT FK_SUBJECT_PULPIT FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT) ON DELETE CASCADE
);
GO

CREATE TABLE TEACHER (
    TEACHER NVARCHAR(100) NOT NULL PRIMARY KEY, 
    TEACHER_NAME NVARCHAR(100) NOT NULL,
    PULPIT NVARCHAR(100) NOT NULL, 
    CONSTRAINT FK_TEACHER_PULPIT FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT) ON DELETE CASCADE
);
GO

CREATE TABLE AUDITORIUM_TYPE (
    AUDITORIUM_TYPE NVARCHAR(100) NOT NULL PRIMARY KEY, 
    AUDITORIUM_TYPENAME NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE AUDITORIUM (
    AUDITORIUM NVARCHAR(100) NOT NULL PRIMARY KEY,
    AUDITORIUM_NAME NVARCHAR(100) NOT NULL,
    AUDITORIUM_CAPACITY INT NOT NULL CHECK (AUDITORIUM_CAPACITY > 0),
    AUDITORIUM_TYPE NVARCHAR(100) NOT NULL, 
    CONSTRAINT FK_AUDITORIUM_TYPE FOREIGN KEY (AUDITORIUM_TYPE)
        REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE) ON DELETE CASCADE
);
GO



INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES
('ИТ', N'Информационных технологий'),
('ИЭФ', N'Инженерно-экономический факультет'),
('ХТИТ', N'Химической технологии и техники');
GO
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY) VALUES
('ИСИТ', N'Информационных систем и технологий', 'ИТ'),
('ПИ', N'Программной инженерии', 'ИТ'),
('ЭУП', N'Экономики и управления на предприятии', 'ИЭФ'),
('ОХ', N'Органической химии', 'ХТИТ');
GO
INSERT INTO SUBJECT (SUBJECT, SUBJECT_NAME, PULPIT) VALUES
('БД', N'Базы данных', 'ИСИТ'),
('ООП', N'Объектно-ориентированное программирование', 'ПИ'),
('ВЭД', N'Внешнеэкономическая деятельность', 'ЭУП'),
('ОХТ', N'Органическая химия и технология', 'ОХ');
GO
INSERT INTO TEACHER (TEACHER, TEACHER_NAME, PULPIT) VALUES
('СМЛВ', N'Смелов Владимир Владиславович', 'ПИ'),
('БЛНВ', N'Блинова Евгения Александровна', 'ИСИТ'),
('ЛДН', N'Ледницкий Андрей Викентьевич', 'ЭУП'),
('ЖРСК', N'Жарский Иван Михайлович', 'ОХ');
GO
INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES
('ЛК', N'Лекционная'),
('ПК', N'Компьютерный класс'),
('ЛБ', N'Лаборатория');
GO
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE) VALUES
('301-1', N'301 корпус 1', 80, 'ЛК'),
('205-4', N'205 корпус 4', 40, 'ПК'),
('105-3', N'Лаб. органики', 20, 'ЛБ'),
('100-1', N'Большая аудитория', 120, 'ЛК');
GO